# Generated by Django 3.2.9 on 2021-12-16 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_redact', models.DateTimeField(blank=True, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Placing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placing_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'placing',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='TypeVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'type_video',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.condition')),
                ('placing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.placing')),
                ('type_video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.typevideo')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_coment', models.TextField(blank=True, null=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.articles')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coment',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
        ),
        migrations.AddField(
            model_name='articles',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.condition'),
        ),
        migrations.AddField(
            model_name='articles',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.source'),
        ),
    ]
