# Generated by Django 3.2.9 on 2021-12-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211216_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='from_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
