# Generated by Django 3.2.9 on 2021-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_redact',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
