# Generated by Django 3.2.9 on 2021-12-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20211217_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condition'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condition'),
        ),
        migrations.AlterField(
            model_name='video',
            name='placing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.placing'),
        ),
        migrations.AlterField(
            model_name='video',
            name='type_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typevideo'),
        ),
    ]
