# Generated by Django 3.2.9 on 2022-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211217_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
