# Generated by Django 3.2.9 on 2022-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_articles_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_views',
            field=models.IntegerField(default=0),
        ),
    ]
